version: '3.7'
services:

  postgres:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=r00dPwt
      - APP_DB_USER=klimawatch
      - APP_DB_PASS=klimawatch
      - APP_DB_NAME=klimawatchdb
    volumes:
      -  ${pgdata}:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"

  klimawatch-server:
    image: sannsie/klimawatch-leipzig:latest
    environment:
      - WAIT_HOSTS=postgres:5432
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30    
      - DB_HOSTNAME=postgres
      - DB_PORT=5432
      - DB_SCHEMA=klimawatchdb
      - DB_USERNAME=klimawatch
      - DB_PASSWORD=klimawatch
    ports:
      - "8081:8080"
    command: sh -c "java -jar /app.jar"
    
